build:
    environment:
        php: '7.4.0'

before_commands:
    - "composer install --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*